// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of info_Info ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class info_InfoViewModel : ViewModelsBase.VMBase, IViewModels.Iinfo_InfoViewModel
    {       

		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		private readonly IServices.ILockScreenService _lockScreenService;
		private readonly Repositories.Iinfo_infoDataSource _info_infoDataSource;
		private readonly Repositories.Ibgkigallery_bgkitumblrfeed _bgkigallery_bgkitumblrfeed;
		private readonly Repositories.Ilatesthairstyles_hairstylefeed _latesthairstyles_hairstylefeed;
		private readonly Repositories.Imakeuptutorials_makeupfeed _makeuptutorials_makeupfeed;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="info_InfoViewModel" /> class.
        /// </summary>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        /// <param name="lockScreenService">The Lock Screen Service.</param>
        /// <param name="info_infoDataSource">The Info_info Data Source.</param>
        /// <param name="bgkigallery_bgkitumblrfeed">The Bgkigallery_bgkitumblrfeed.</param>
        /// <param name="latesthairstyles_hairstylefeed">The Latesthairstyles_hairstylefeed.</param>
        /// <param name="makeuptutorials_makeupfeed">The Makeuptutorials_makeupfeed.</param>
        public info_InfoViewModel(IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService, IServices.ILockScreenService lockScreenService, Repositories.Iinfo_infoDataSource info_infoDataSource, Repositories.Ibgkigallery_bgkitumblrfeed bgkigallery_bgkitumblrfeed, Repositories.Ilatesthairstyles_hairstylefeed latesthairstyles_hairstylefeed, Repositories.Imakeuptutorials_makeupfeed makeuptutorials_makeupfeed)
        {
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
			_lockScreenService = lockScreenService;
			_info_infoDataSource = info_infoDataSource;
			_bgkigallery_bgkitumblrfeed = bgkigallery_bgkitumblrfeed;
			_latesthairstyles_hairstylefeed = latesthairstyles_hairstylefeed;
			_makeuptutorials_makeupfeed = makeuptutorials_makeupfeed;
        }
		
	
		private string _currentinfo_InfoHtmlControl;

        /// <summary>
        /// Currentinfo_InfoHtmlControl property.
        /// </summary>		
        public string Currentinfo_InfoHtmlControl
        {
            get
            {
				
                if(_currentinfo_InfoHtmlControl == null)
					_currentinfo_InfoHtmlControl = _info_infoDataSource.Get();
				return _currentinfo_InfoHtmlControl;     
            }
            set
            {
                SetProperty(ref _currentinfo_InfoHtmlControl, value);
            }
        }
	
		private ObservableCollection<EntitiesBase.RssSearchResult> _bgkigallery_NewsListControlCollection;

        /// <summary>
        /// Bgkigallery_NewsListControlCollection property.
        /// </summary>		
        public ObservableCollection<EntitiesBase.RssSearchResult> Bgkigallery_NewsListControlCollection
        {
            get
            {
				
                if(_bgkigallery_NewsListControlCollection == null)
					Getbgkigallery_NewsListControlCollectionData();
				return _bgkigallery_NewsListControlCollection;     
            }
            set
            {
                SetProperty(ref _bgkigallery_NewsListControlCollection, value);
            }
        }
	
		private EntitiesBase.RssSearchResult _selectedbgkigallery_NewsListControlCollection;

        /// <summary>
        /// Selectedbgkigallery_NewsListControlCollection property.
        /// </summary>		
        public EntitiesBase.RssSearchResult Selectedbgkigallery_NewsListControlCollection
        {
            get
            {
				return _selectedbgkigallery_NewsListControlCollection;
            }
            set
            {
                _selectedbgkigallery_NewsListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.Ibgkigallery_DetailViewModel>(_selectedbgkigallery_NewsListControlCollection);
            }
        }
	
		private ObservableCollection<EntitiesBase.RssSearchResult> _latesthairstyles_NewsListControlCollection;

        /// <summary>
        /// Latesthairstyles_NewsListControlCollection property.
        /// </summary>		
        public ObservableCollection<EntitiesBase.RssSearchResult> Latesthairstyles_NewsListControlCollection
        {
            get
            {
				
                if(_latesthairstyles_NewsListControlCollection == null)
					Getlatesthairstyles_NewsListControlCollectionData();
				return _latesthairstyles_NewsListControlCollection;     
            }
            set
            {
                SetProperty(ref _latesthairstyles_NewsListControlCollection, value);
            }
        }
	
		private EntitiesBase.RssSearchResult _selectedlatesthairstyles_NewsListControlCollection;

        /// <summary>
        /// Selectedlatesthairstyles_NewsListControlCollection property.
        /// </summary>		
        public EntitiesBase.RssSearchResult Selectedlatesthairstyles_NewsListControlCollection
        {
            get
            {
				return _selectedlatesthairstyles_NewsListControlCollection;
            }
            set
            {
                _selectedlatesthairstyles_NewsListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.Ilatesthairstyles_DetailViewModel>(_selectedlatesthairstyles_NewsListControlCollection);
            }
        }
	
		private ObservableCollection<EntitiesBase.RssSearchResult> _makeuptutorials_NewsListControlCollection;

        /// <summary>
        /// Makeuptutorials_NewsListControlCollection property.
        /// </summary>		
        public ObservableCollection<EntitiesBase.RssSearchResult> Makeuptutorials_NewsListControlCollection
        {
            get
            {
				
                if(_makeuptutorials_NewsListControlCollection == null)
					Getmakeuptutorials_NewsListControlCollectionData();
				return _makeuptutorials_NewsListControlCollection;     
            }
            set
            {
                SetProperty(ref _makeuptutorials_NewsListControlCollection, value);
            }
        }
	
		private EntitiesBase.RssSearchResult _selectedmakeuptutorials_NewsListControlCollection;

        /// <summary>
        /// Selectedmakeuptutorials_NewsListControlCollection property.
        /// </summary>		
        public EntitiesBase.RssSearchResult Selectedmakeuptutorials_NewsListControlCollection
        {
            get
            {
				return _selectedmakeuptutorials_NewsListControlCollection;
            }
            set
            {
                _selectedmakeuptutorials_NewsListControlCollection = value;
                if (value != null)
                    _navigationService.NavigateTo<IViewModels.Imakeuptutorials_DetailViewModel>(_selectedmakeuptutorials_NewsListControlCollection);
            }
        }

        /// <summary>
        /// Delegate method for the Refreshbgkigallery_NewsListControlCollectionCommand command.
        /// </summary>
        public async void Refreshbgkigallery_NewsListControlCollectionCommandDelegate() 
        {
			try
			{
				LoadingBgkigallery_NewsListControlCollection = true;
				var items = await  _bgkigallery_bgkitumblrfeed.Refresh();
				Bgkigallery_NewsListControlCollection = items;
			}
            catch (Exception ex)
            {
				Bgkigallery_NewsListControlCollection = null;
		
                Debug.WriteLine(ex.ToString());
                _dialogService.Show(Localization.AppResources.rssError + Environment.NewLine + Localization.AppResources.TryAgain);
            }
            finally
            {
				LoadingBgkigallery_NewsListControlCollection = false;
			}
        }
		
		
        private bool _loadingBgkigallery_NewsListControlCollection;
		
        public bool LoadingBgkigallery_NewsListControlCollection
        {
            get { return _loadingBgkigallery_NewsListControlCollection; }
            set { SetProperty(ref _loadingBgkigallery_NewsListControlCollection, value); }
        }

        private ICommand _refreshbgkigallery_NewsListControlCollectionCommand;

        /// <summary>
        /// Gets the Refreshbgkigallery_NewsListControlCollectionCommand command.
        /// </summary>
        public ICommand Refreshbgkigallery_NewsListControlCollectionCommand
        {
            get { return _refreshbgkigallery_NewsListControlCollectionCommand = _refreshbgkigallery_NewsListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand(Refreshbgkigallery_NewsListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Getbgkigallery_NewsListControlCollectionCommand command.
        /// </summary>
        public  void Getbgkigallery_NewsListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				Getbgkigallery_NewsListControlCollectionData(pageNumber);
        }
		

        private ICommand _getbgkigallery_NewsListControlCollectionCommand;

        /// <summary>
        /// Gets the Getbgkigallery_NewsListControlCollectionCommand command.
        /// </summary>
        public ICommand Getbgkigallery_NewsListControlCollectionCommand
        {
            get { return _getbgkigallery_NewsListControlCollectionCommand = _getbgkigallery_NewsListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(Getbgkigallery_NewsListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Refreshlatesthairstyles_NewsListControlCollectionCommand command.
        /// </summary>
        public async void Refreshlatesthairstyles_NewsListControlCollectionCommandDelegate() 
        {
			try
			{
				LoadingLatesthairstyles_NewsListControlCollection = true;
				var items = await  _latesthairstyles_hairstylefeed.Refresh();
				Latesthairstyles_NewsListControlCollection = items;
			}
            catch (Exception ex)
            {
				Latesthairstyles_NewsListControlCollection = null;
		
                Debug.WriteLine(ex.ToString());
                _dialogService.Show(Localization.AppResources.rssError + Environment.NewLine + Localization.AppResources.TryAgain);
            }
            finally
            {
				LoadingLatesthairstyles_NewsListControlCollection = false;
			}
        }
		
		
        private bool _loadingLatesthairstyles_NewsListControlCollection;
		
        public bool LoadingLatesthairstyles_NewsListControlCollection
        {
            get { return _loadingLatesthairstyles_NewsListControlCollection; }
            set { SetProperty(ref _loadingLatesthairstyles_NewsListControlCollection, value); }
        }

        private ICommand _refreshlatesthairstyles_NewsListControlCollectionCommand;

        /// <summary>
        /// Gets the Refreshlatesthairstyles_NewsListControlCollectionCommand command.
        /// </summary>
        public ICommand Refreshlatesthairstyles_NewsListControlCollectionCommand
        {
            get { return _refreshlatesthairstyles_NewsListControlCollectionCommand = _refreshlatesthairstyles_NewsListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand(Refreshlatesthairstyles_NewsListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Getlatesthairstyles_NewsListControlCollectionCommand command.
        /// </summary>
        public  void Getlatesthairstyles_NewsListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				Getlatesthairstyles_NewsListControlCollectionData(pageNumber);
        }
		

        private ICommand _getlatesthairstyles_NewsListControlCollectionCommand;

        /// <summary>
        /// Gets the Getlatesthairstyles_NewsListControlCollectionCommand command.
        /// </summary>
        public ICommand Getlatesthairstyles_NewsListControlCollectionCommand
        {
            get { return _getlatesthairstyles_NewsListControlCollectionCommand = _getlatesthairstyles_NewsListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(Getlatesthairstyles_NewsListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Refreshmakeuptutorials_NewsListControlCollectionCommand command.
        /// </summary>
        public async void Refreshmakeuptutorials_NewsListControlCollectionCommandDelegate() 
        {
			try
			{
				LoadingMakeuptutorials_NewsListControlCollection = true;
				var items = await  _makeuptutorials_makeupfeed.Refresh();
				Makeuptutorials_NewsListControlCollection = items;
			}
            catch (Exception ex)
            {
				Makeuptutorials_NewsListControlCollection = null;
		
                Debug.WriteLine(ex.ToString());
                _dialogService.Show(Localization.AppResources.rssError + Environment.NewLine + Localization.AppResources.TryAgain);
            }
            finally
            {
				LoadingMakeuptutorials_NewsListControlCollection = false;
			}
        }
		
		
        private bool _loadingMakeuptutorials_NewsListControlCollection;
		
        public bool LoadingMakeuptutorials_NewsListControlCollection
        {
            get { return _loadingMakeuptutorials_NewsListControlCollection; }
            set { SetProperty(ref _loadingMakeuptutorials_NewsListControlCollection, value); }
        }

        private ICommand _refreshmakeuptutorials_NewsListControlCollectionCommand;

        /// <summary>
        /// Gets the Refreshmakeuptutorials_NewsListControlCollectionCommand command.
        /// </summary>
        public ICommand Refreshmakeuptutorials_NewsListControlCollectionCommand
        {
            get { return _refreshmakeuptutorials_NewsListControlCollectionCommand = _refreshmakeuptutorials_NewsListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand(Refreshmakeuptutorials_NewsListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Getmakeuptutorials_NewsListControlCollectionCommand command.
        /// </summary>
        public  void Getmakeuptutorials_NewsListControlCollectionCommandDelegate(int pageNumber= 0) 
        {
				Getmakeuptutorials_NewsListControlCollectionData(pageNumber);
        }
		

        private ICommand _getmakeuptutorials_NewsListControlCollectionCommand;

        /// <summary>
        /// Gets the Getmakeuptutorials_NewsListControlCollectionCommand command.
        /// </summary>
        public ICommand Getmakeuptutorials_NewsListControlCollectionCommand
        {
            get { return _getmakeuptutorials_NewsListControlCollectionCommand = _getmakeuptutorials_NewsListControlCollectionCommand ?? new ViewModelsBase.DelegateCommand<int>(Getmakeuptutorials_NewsListControlCollectionCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechinfo_InfoHtmlControlCommand command.
        /// </summary>
        public  void TextToSpeechinfo_InfoHtmlControlCommandDelegate() 
        {
				_speechService.TextToSpeech(Currentinfo_InfoHtmlControl);
        }
		

        private ICommand _textToSpeechinfo_InfoHtmlControlCommand;

        /// <summary>
        /// Gets the TextToSpeechinfo_InfoHtmlControlCommand command.
        /// </summary>
        public ICommand TextToSpeechinfo_InfoHtmlControlCommand
        {
            get { return _textToSpeechinfo_InfoHtmlControlCommand = _textToSpeechinfo_InfoHtmlControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechinfo_InfoHtmlControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Shareinfo_InfoHtmlControlCommand command.
        /// </summary>
        public  void Shareinfo_InfoHtmlControlCommandDelegate() 
        {
				_shareService.Share(@"info", Currentinfo_InfoHtmlControl);
        }
		

        private ICommand _shareinfo_InfoHtmlControlCommand;

        /// <summary>
        /// Gets the Shareinfo_InfoHtmlControlCommand command.
        /// </summary>
        public ICommand Shareinfo_InfoHtmlControlCommand
        {
            get { return _shareinfo_InfoHtmlControlCommand = _shareinfo_InfoHtmlControlCommand ?? new ViewModelsBase.DelegateCommand(Shareinfo_InfoHtmlControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartinfo_InfoHtmlControlCommand command.
        /// </summary>
        public  void PinToStartinfo_InfoHtmlControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.Iinfo_InfoViewModel), CreateTileInfoinfo_InfoHtmlControl());
        }
		

        private ICommand _pinToStartinfo_InfoHtmlControlCommand;

        /// <summary>
        /// Gets the PinToStartinfo_InfoHtmlControlCommand command.
        /// </summary>
        public ICommand PinToStartinfo_InfoHtmlControlCommand
        {
            get { return _pinToStartinfo_InfoHtmlControlCommand = _pinToStartinfo_InfoHtmlControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartinfo_InfoHtmlControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the SetLockScreenCommand command.
        /// </summary>
        public  void SetLockScreenCommandDelegate() 
        {
				_lockScreenService.SetLockScreen("LockScreen-b960fc10-5c97-426b-b78d-6dc981576002.jpg");
        }
		

        private ICommand _setLockScreenCommand;

        /// <summary>
        /// Gets the SetLockScreenCommand command.
        /// </summary>
        public ICommand SetLockScreenCommand
        {
            get { return _setLockScreenCommand = _setLockScreenCommand ?? new ViewModelsBase.DelegateCommand(SetLockScreenCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the AboutCommand command.
        /// </summary>
        public  void AboutCommandDelegate() 
        {
				_navigationService.NavigateTo<IViewModels.IAboutViewModel>();
        }
		

        private ICommand _aboutCommand;

        /// <summary>
        /// Gets the AboutCommand command.
        /// </summary>
        public ICommand AboutCommand
        {
            get { return _aboutCommand = _aboutCommand ?? new ViewModelsBase.DelegateCommand(AboutCommandDelegate); }
        }

        private async void Getbgkigallery_NewsListControlCollectionData(int pageNumber = 0)
        {
	
			try
			{
				LoadingBgkigallery_NewsListControlCollection = true;
			
				var items = await _bgkigallery_bgkitumblrfeed.GetData();
                Bgkigallery_NewsListControlCollection = items;
			}
            catch (Exception ex)
            {
				Bgkigallery_NewsListControlCollection = null;
		
                Debug.WriteLine(ex.ToString());
                _dialogService.Show(Localization.AppResources.rssError + Environment.NewLine + Localization.AppResources.TryAgain);
            }
            finally
            {
				LoadingBgkigallery_NewsListControlCollection = false;
			}
		}

        private async void Getlatesthairstyles_NewsListControlCollectionData(int pageNumber = 0)
        {
	
			try
			{
				LoadingLatesthairstyles_NewsListControlCollection = true;
			
				var items = await _latesthairstyles_hairstylefeed.GetData();
                Latesthairstyles_NewsListControlCollection = items;
			}
            catch (Exception ex)
            {
				Latesthairstyles_NewsListControlCollection = null;
		
                Debug.WriteLine(ex.ToString());
                _dialogService.Show(Localization.AppResources.rssError + Environment.NewLine + Localization.AppResources.TryAgain);
            }
            finally
            {
				LoadingLatesthairstyles_NewsListControlCollection = false;
			}
		}

        private async void Getmakeuptutorials_NewsListControlCollectionData(int pageNumber = 0)
        {
	
			try
			{
				LoadingMakeuptutorials_NewsListControlCollection = true;
			
				var items = await _makeuptutorials_makeupfeed.GetData();
                Makeuptutorials_NewsListControlCollection = items;
			}
            catch (Exception ex)
            {
				Makeuptutorials_NewsListControlCollection = null;
		
                Debug.WriteLine(ex.ToString());
                _dialogService.Show(Localization.AppResources.rssError + Environment.NewLine + Localization.AppResources.TryAgain);
            }
            finally
            {
				LoadingMakeuptutorials_NewsListControlCollection = false;
			}
		}
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the info_InfoHtmlControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfoinfo_InfoHtmlControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = @"info",
                Title = @"info",
                BackTitle = @"info",
                BackContent = Currentinfo_InfoHtmlControl,
                Count = 0,
                BackgroundImagePath = string.Empty,
                BackBackgroundImagePath = string.Empty,
                LogoPath = "Logo-cfb601a5-b86b-4c80-963d-208f9e1498e4.png"
            };
            return tileInfo;
        }
    }
}
