// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of latesthairstyles_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class latesthairstyles_DetailViewModel : ViewModelsBase.VMBase, IViewModels.Ilatesthairstyles_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.latesthairstyles_hairstylefeed _latesthairstyles_hairstylefeed;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="latesthairstyles_DetailViewModel" /> class.
        /// </summary>
        /// <param name="latesthairstyles_hairstylefeed">The Latesthairstyles_hairstylefeed.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public latesthairstyles_DetailViewModel(Repositories.latesthairstyles_hairstylefeed latesthairstyles_hairstylefeed, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_latesthairstyles_hairstylefeed = latesthairstyles_hairstylefeed;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }
	
		private bool _hasNextpanoramalatesthairstyles_Detail0;

        /// <summary>
        /// HasNextpanoramalatesthairstyles_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramalatesthairstyles_Detail0
        {
            get
            {
				return _hasNextpanoramalatesthairstyles_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramalatesthairstyles_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramalatesthairstyles_Detail0;

        /// <summary>
        /// HasPreviouspanoramalatesthairstyles_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramalatesthairstyles_Detail0
        {
            get
            {
				return _hasPreviouspanoramalatesthairstyles_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramalatesthairstyles_Detail0, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechlatesthairstyles_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechlatesthairstyles_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechlatesthairstyles_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechlatesthairstyles_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechlatesthairstyles_DetailStaticControlCommand
        {
            get { return _textToSpeechlatesthairstyles_DetailStaticControlCommand = _textToSpeechlatesthairstyles_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechlatesthairstyles_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Sharelatesthairstyles_DetailStaticControlCommand command.
        /// </summary>
        public  void Sharelatesthairstyles_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Content, CurrentRssSearchResult.FeedUrl, CurrentRssSearchResult.ImageUrl);
        }
		

        private ICommand _sharelatesthairstyles_DetailStaticControlCommand;

        /// <summary>
        /// Gets the Sharelatesthairstyles_DetailStaticControlCommand command.
        /// </summary>
        public ICommand Sharelatesthairstyles_DetailStaticControlCommand
        {
            get { return _sharelatesthairstyles_DetailStaticControlCommand = _sharelatesthairstyles_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(Sharelatesthairstyles_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartlatesthairstyles_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartlatesthairstyles_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.Ilatesthairstyles_DetailViewModel), CreateTileInfolatesthairstyles_DetailStaticControl());
        }
		

        private ICommand _pinToStartlatesthairstyles_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartlatesthairstyles_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartlatesthairstyles_DetailStaticControlCommand
        {
            get { return _pinToStartlatesthairstyles_DetailStaticControlCommand = _pinToStartlatesthairstyles_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartlatesthairstyles_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourcelatesthairstyles_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourcelatesthairstyles_DetailStaticControlCommandDelegate() 
        {
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourcelatesthairstyles_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourcelatesthairstyles_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourcelatesthairstyles_DetailStaticControlCommand
        {
            get { return _goToSourcelatesthairstyles_DetailStaticControlCommand = _goToSourcelatesthairstyles_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourcelatesthairstyles_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Nextpanoramalatesthairstyles_Detail0 command.
        /// </summary>
        public async void Nextpanoramalatesthairstyles_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var next = await  _latesthairstyles_hairstylefeed.Next(CurrentRssSearchResult);

			if(next != null)
				CurrentRssSearchResult = next;

			RefreshHasPrevNext();
        }
		
		
        private bool _loadingCurrentRssSearchResult;
		
        public bool LoadingCurrentRssSearchResult
        {
            get { return _loadingCurrentRssSearchResult; }
            set { SetProperty(ref _loadingCurrentRssSearchResult, value); }
        }

        private ICommand _nextpanoramalatesthairstyles_Detail0;

        /// <summary>
        /// Gets the Nextpanoramalatesthairstyles_Detail0 command.
        /// </summary>
        public ICommand Nextpanoramalatesthairstyles_Detail0
        {
            get { return _nextpanoramalatesthairstyles_Detail0 = _nextpanoramalatesthairstyles_Detail0 ?? new ViewModelsBase.DelegateCommand(Nextpanoramalatesthairstyles_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the Previouspanoramalatesthairstyles_Detail0 command.
        /// </summary>
        public async void Previouspanoramalatesthairstyles_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var prev = await  _latesthairstyles_hairstylefeed.Previous(CurrentRssSearchResult);

			if(prev != null)
				CurrentRssSearchResult = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramalatesthairstyles_Detail0;

        /// <summary>
        /// Gets the Previouspanoramalatesthairstyles_Detail0 command.
        /// </summary>
        public ICommand Previouspanoramalatesthairstyles_Detail0
        {
            get { return _previouspanoramalatesthairstyles_Detail0 = _previouspanoramalatesthairstyles_Detail0 ?? new ViewModelsBase.DelegateCommand(Previouspanoramalatesthairstyles_Detail0Delegate); }
        }

        private async void RefreshHasPrevNext()
        {
            HasPreviouspanoramalatesthairstyles_Detail0 = await _latesthairstyles_hairstylefeed.HasPrevious(CurrentRssSearchResult);
			HasNextpanoramalatesthairstyles_Detail0 = await _latesthairstyles_hairstylefeed.HasNext(CurrentRssSearchResult);
			LoadingCurrentRssSearchResult = false;
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the latesthairstyles_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfolatesthairstyles_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "Logo-cfb601a5-b86b-4c80-963d-208f9e1498e4.png"
            };
            return tileInfo;
        }
    }
}
