// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	ViewModel.tt
// Version:		2.0
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Controls = WPAppStudio.Controls;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;
using IServices = WPAppStudio.Services.Interfaces;
using IViewModels = WPAppStudio.ViewModel.Interfaces;
using Localization = WPAppStudio.Localization;
using Repositories = WPAppStudio.Repositories;
using Services = WPAppStudio.Services;
using ViewModelsBase = WPAppStudio.ViewModel.Base;
using WPAppStudio;
using WPAppStudio.Shared;

namespace WPAppStudio.ViewModel
{
    /// <summary>
    /// Implementation of makeuptutorials_Detail ViewModel.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public partial class makeuptutorials_DetailViewModel : ViewModelsBase.VMBase, IViewModels.Imakeuptutorials_DetailViewModel, ViewModelsBase.INavigable
    {       

		private readonly Repositories.makeuptutorials_makeupfeed _makeuptutorials_makeupfeed;
		private readonly IServices.IDialogService _dialogService;
		private readonly IServices.INavigationService _navigationService;
		private readonly IServices.ISpeechService _speechService;
		private readonly IServices.IShareService _shareService;
		private readonly IServices.ILiveTileService _liveTileService;
		
        /// <summary>
        /// Initializes a new instance of the <see cref="makeuptutorials_DetailViewModel" /> class.
        /// </summary>
        /// <param name="makeuptutorials_makeupfeed">The Makeuptutorials_makeupfeed.</param>
        /// <param name="dialogService">The Dialog Service.</param>
        /// <param name="navigationService">The Navigation Service.</param>
        /// <param name="speechService">The Speech Service.</param>
        /// <param name="shareService">The Share Service.</param>
        /// <param name="liveTileService">The Live Tile Service.</param>
        public makeuptutorials_DetailViewModel(Repositories.makeuptutorials_makeupfeed makeuptutorials_makeupfeed, IServices.IDialogService dialogService, IServices.INavigationService navigationService, IServices.ISpeechService speechService, IServices.IShareService shareService, IServices.ILiveTileService liveTileService)
        {
			_makeuptutorials_makeupfeed = makeuptutorials_makeupfeed;
			_dialogService = dialogService;
			_navigationService = navigationService;
			_speechService = speechService;
			_shareService = shareService;
			_liveTileService = liveTileService;
        }
		
	
		private EntitiesBase.RssSearchResult _currentRssSearchResult;

        /// <summary>
        /// CurrentRssSearchResult property.
        /// </summary>		
        public EntitiesBase.RssSearchResult CurrentRssSearchResult
        {
            get
            {
				return _currentRssSearchResult;
            }
            set
            {
                SetProperty(ref _currentRssSearchResult, value);
            }
        }
	
		private bool _hasNextpanoramamakeuptutorials_Detail0;

        /// <summary>
        /// HasNextpanoramamakeuptutorials_Detail0 property.
        /// </summary>		
        public bool HasNextpanoramamakeuptutorials_Detail0
        {
            get
            {
				return _hasNextpanoramamakeuptutorials_Detail0;
            }
            set
            {
                SetProperty(ref _hasNextpanoramamakeuptutorials_Detail0, value);
            }
        }
	
		private bool _hasPreviouspanoramamakeuptutorials_Detail0;

        /// <summary>
        /// HasPreviouspanoramamakeuptutorials_Detail0 property.
        /// </summary>		
        public bool HasPreviouspanoramamakeuptutorials_Detail0
        {
            get
            {
				return _hasPreviouspanoramamakeuptutorials_Detail0;
            }
            set
            {
                SetProperty(ref _hasPreviouspanoramamakeuptutorials_Detail0, value);
            }
        }

        /// <summary>
        /// Delegate method for the TextToSpeechmakeuptutorials_DetailStaticControlCommand command.
        /// </summary>
        public  void TextToSpeechmakeuptutorials_DetailStaticControlCommandDelegate() 
        {
				_speechService.TextToSpeech(CurrentRssSearchResult.Title + " " + CurrentRssSearchResult.Content);
        }
		

        private ICommand _textToSpeechmakeuptutorials_DetailStaticControlCommand;

        /// <summary>
        /// Gets the TextToSpeechmakeuptutorials_DetailStaticControlCommand command.
        /// </summary>
        public ICommand TextToSpeechmakeuptutorials_DetailStaticControlCommand
        {
            get { return _textToSpeechmakeuptutorials_DetailStaticControlCommand = _textToSpeechmakeuptutorials_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(TextToSpeechmakeuptutorials_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Sharemakeuptutorials_DetailStaticControlCommand command.
        /// </summary>
        public  void Sharemakeuptutorials_DetailStaticControlCommandDelegate() 
        {
				_shareService.Share(CurrentRssSearchResult.Title, CurrentRssSearchResult.Content, CurrentRssSearchResult.FeedUrl, CurrentRssSearchResult.ImageUrl);
        }
		

        private ICommand _sharemakeuptutorials_DetailStaticControlCommand;

        /// <summary>
        /// Gets the Sharemakeuptutorials_DetailStaticControlCommand command.
        /// </summary>
        public ICommand Sharemakeuptutorials_DetailStaticControlCommand
        {
            get { return _sharemakeuptutorials_DetailStaticControlCommand = _sharemakeuptutorials_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(Sharemakeuptutorials_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the PinToStartmakeuptutorials_DetailStaticControlCommand command.
        /// </summary>
        public  void PinToStartmakeuptutorials_DetailStaticControlCommandDelegate() 
        {
				_liveTileService.PinToStart(typeof(IViewModels.Imakeuptutorials_DetailViewModel), CreateTileInfomakeuptutorials_DetailStaticControl());
        }
		

        private ICommand _pinToStartmakeuptutorials_DetailStaticControlCommand;

        /// <summary>
        /// Gets the PinToStartmakeuptutorials_DetailStaticControlCommand command.
        /// </summary>
        public ICommand PinToStartmakeuptutorials_DetailStaticControlCommand
        {
            get { return _pinToStartmakeuptutorials_DetailStaticControlCommand = _pinToStartmakeuptutorials_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(PinToStartmakeuptutorials_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the GoToSourcemakeuptutorials_DetailStaticControlCommand command.
        /// </summary>
        public  void GoToSourcemakeuptutorials_DetailStaticControlCommandDelegate() 
        {
				_navigationService.NavigateTo(string.IsNullOrEmpty(CurrentRssSearchResult.FeedUrl) ? null : new Uri(CurrentRssSearchResult.FeedUrl));
        }
		

        private ICommand _goToSourcemakeuptutorials_DetailStaticControlCommand;

        /// <summary>
        /// Gets the GoToSourcemakeuptutorials_DetailStaticControlCommand command.
        /// </summary>
        public ICommand GoToSourcemakeuptutorials_DetailStaticControlCommand
        {
            get { return _goToSourcemakeuptutorials_DetailStaticControlCommand = _goToSourcemakeuptutorials_DetailStaticControlCommand ?? new ViewModelsBase.DelegateCommand(GoToSourcemakeuptutorials_DetailStaticControlCommandDelegate); }
        }

        /// <summary>
        /// Delegate method for the Nextpanoramamakeuptutorials_Detail0 command.
        /// </summary>
        public async void Nextpanoramamakeuptutorials_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var next = await  _makeuptutorials_makeupfeed.Next(CurrentRssSearchResult);

			if(next != null)
				CurrentRssSearchResult = next;

			RefreshHasPrevNext();
        }
		
		
        private bool _loadingCurrentRssSearchResult;
		
        public bool LoadingCurrentRssSearchResult
        {
            get { return _loadingCurrentRssSearchResult; }
            set { SetProperty(ref _loadingCurrentRssSearchResult, value); }
        }

        private ICommand _nextpanoramamakeuptutorials_Detail0;

        /// <summary>
        /// Gets the Nextpanoramamakeuptutorials_Detail0 command.
        /// </summary>
        public ICommand Nextpanoramamakeuptutorials_Detail0
        {
            get { return _nextpanoramamakeuptutorials_Detail0 = _nextpanoramamakeuptutorials_Detail0 ?? new ViewModelsBase.DelegateCommand(Nextpanoramamakeuptutorials_Detail0Delegate); }
        }

        /// <summary>
        /// Delegate method for the Previouspanoramamakeuptutorials_Detail0 command.
        /// </summary>
        public async void Previouspanoramamakeuptutorials_Detail0Delegate() 
        {
				LoadingCurrentRssSearchResult = true;
			var prev = await  _makeuptutorials_makeupfeed.Previous(CurrentRssSearchResult);

			if(prev != null)
				CurrentRssSearchResult = prev;

			RefreshHasPrevNext();
        }
		

        private ICommand _previouspanoramamakeuptutorials_Detail0;

        /// <summary>
        /// Gets the Previouspanoramamakeuptutorials_Detail0 command.
        /// </summary>
        public ICommand Previouspanoramamakeuptutorials_Detail0
        {
            get { return _previouspanoramamakeuptutorials_Detail0 = _previouspanoramamakeuptutorials_Detail0 ?? new ViewModelsBase.DelegateCommand(Previouspanoramamakeuptutorials_Detail0Delegate); }
        }

        private async void RefreshHasPrevNext()
        {
            HasPreviouspanoramamakeuptutorials_Detail0 = await _makeuptutorials_makeupfeed.HasPrevious(CurrentRssSearchResult);
			HasNextpanoramamakeuptutorials_Detail0 = await _makeuptutorials_makeupfeed.HasNext(CurrentRssSearchResult);
			LoadingCurrentRssSearchResult = false;
		}
		public object NavigationContext
        {
            set
            {              
                if (!(value is EntitiesBase.RssSearchResult)) { return; }
                
                CurrentRssSearchResult = value as EntitiesBase.RssSearchResult;
                RefreshHasPrevNext();
            }
        }
        /// <summary>
        /// Initializes a <see cref="Services.TileInfo" /> object for the makeuptutorials_DetailStaticControl control.
        /// </summary>
		/// <returns>A <see cref="Services.TileInfo" /> object.</returns>
        public Services.TileInfo CreateTileInfomakeuptutorials_DetailStaticControl()
        {
            var tileInfo = new Services.TileInfo
            {
                CurrentId = CurrentRssSearchResult.Title,
                Title = CurrentRssSearchResult.Title,
                BackTitle = CurrentRssSearchResult.Title,
                BackContent = CurrentRssSearchResult.Content,
                Count = 0,
                BackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                BackBackgroundImagePath = CurrentRssSearchResult.ImageUrl,
                LogoPath = "Logo-cfb601a5-b86b-4c80-963d-208f9e1498e4.png"
            };
            return tileInfo;
        }
    }
}
