// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// bgkigallery_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Ibgkigallery_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramabgkigallery_Detail0 property.
        /// </summary>
		bool HasNextpanoramabgkigallery_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramabgkigallery_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramabgkigallery_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechbgkigallery_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechbgkigallery_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Sharebgkigallery_DetailStaticControlCommand command.
        /// </summary>
		ICommand Sharebgkigallery_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartbgkigallery_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartbgkigallery_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourcebgkigallery_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourcebgkigallery_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Nextpanoramabgkigallery_Detail0 command.
        /// </summary>
		ICommand Nextpanoramabgkigallery_Detail0 { get; }

        
        /// <summary>
        /// Gets the Previouspanoramabgkigallery_Detail0 command.
        /// </summary>
		ICommand Previouspanoramabgkigallery_Detail0 { get; }

	}
}
