// ------------------------------------------------------------------------
// ========================================================================
// THIS CODE AND INFORMATION ARE GENERATED BY AUTOMATIC CODE GENERATOR
// ========================================================================
// Template:   	IViewModel.tt
// Version:		2.0
using System.CodeDom.Compiler;
using System.Collections.ObjectModel;
using System.Runtime.CompilerServices;
using System.Windows;
using System.Windows.Input;
using Entities = WPAppStudio.Entities;
using EntitiesBase = WPAppStudio.Entities.Base;

namespace WPAppStudio.ViewModel.Interfaces
{
    /// <summary>
    /// latesthairstyles_Detail ViewModel interface.
    /// </summary>
    [CompilerGenerated]
    [GeneratedCode("Radarc", "4.0")]
    public interface Ilatesthairstyles_DetailViewModel
    {		
        /// <summary>
        /// Gets/Sets the CurrentRssSearchResult property.
        /// </summary>
		EntitiesBase.RssSearchResult CurrentRssSearchResult { get; set; }
        /// <summary>
        /// Gets/Sets the HasNextpanoramalatesthairstyles_Detail0 property.
        /// </summary>
		bool HasNextpanoramalatesthairstyles_Detail0 { get; set; }
        /// <summary>
        /// Gets/Sets the HasPreviouspanoramalatesthairstyles_Detail0 property.
        /// </summary>
		bool HasPreviouspanoramalatesthairstyles_Detail0 { get; set; }
        
        /// <summary>
        /// Gets the TextToSpeechlatesthairstyles_DetailStaticControlCommand command.
        /// </summary>
		ICommand TextToSpeechlatesthairstyles_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Sharelatesthairstyles_DetailStaticControlCommand command.
        /// </summary>
		ICommand Sharelatesthairstyles_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the PinToStartlatesthairstyles_DetailStaticControlCommand command.
        /// </summary>
		ICommand PinToStartlatesthairstyles_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the GoToSourcelatesthairstyles_DetailStaticControlCommand command.
        /// </summary>
		ICommand GoToSourcelatesthairstyles_DetailStaticControlCommand { get; }

        
        /// <summary>
        /// Gets the Nextpanoramalatesthairstyles_Detail0 command.
        /// </summary>
		ICommand Nextpanoramalatesthairstyles_Detail0 { get; }

        
        /// <summary>
        /// Gets the Previouspanoramalatesthairstyles_Detail0 command.
        /// </summary>
		ICommand Previouspanoramalatesthairstyles_Detail0 { get; }

	}
}
